name: Cron Test

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Cron is working!"

      - name: Show current time
        run: date
